<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="INBook_X1" failures="1" tests="2" name="TestCases" time="0.096" errors="0" timestamp="2025-03-25T19:03:14 IST">
  <testcase classname="tests.LoginTest" name="loginTest" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.io.FileNotFoundException: src\test\resources\testdata.xlsx (The system cannot find the path specified)">
      <![CDATA[java.lang.RuntimeException: java.io.FileNotFoundException: src\test\resources\testdata.xlsx (The system cannot find the path specified)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.io.FileNotFoundException: src\test\resources\testdata.xlsx (The system cannot find the path specified)
at java.base/java.io.FileInputStream.open0(Native Method)
at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
at utils.ExcelUtil.getExcelData(ExcelUtil.java:12)
at dataprovider.DataProviderClass.getTestData(DataProviderClass.java:9)
... 25 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase classname="tests.SearchTest" name="searchTest" time="0.005"/>
</testsuite> <!-- TestCases -->
